#!/usr/bin/python3
from sys import argv
import math


with open(argv[1], 'r') as f:
    for line in f:
        line = line.strip()
        num = int(line)
        for i in range(2, int(math.sqrt(num)) + 1):
            if num % i == 0:
                print(f"{num}={int(num/i)}*{i}")
                break
